enum PokemonsListActions {
  'POKEMONS_LIST_LOADING' = 'POKEMONS_LIST_LOADING',
  'POKEMINS_LIST_LOADED' = 'POKEMINS_LIST_LOADED',
  'POKEMONS_LIST_LOAD_ERROR' = 'POKEMONS_LIST_LOAD_ERROR',
}

enum PokemonActions {
  'POKEMON_LOADING' = 'POKEMON_LOADING',
  'POKEMIN_LOADED' = 'POKEMIN_LOADED',
  'POKEMON_LOAD_ERROR' = 'POKEMON_LOAD_ERROR',
}

enum PokemonAbilityActions {
  'ABILITY_LOADING' = 'ABILITY_LOADING',
  'ABILITY_LOADED' = 'ABILITY_LOADED',
  'ABILITY_LOAD_ERROR' = 'ABILITY_LOAD_ERROR',
}

export { PokemonsListActions, PokemonActions, PokemonAbilityActions };
